# Ex2 - Getting and Knowing your Data

Check out [Chipotle Exercises Video Tutorial](https://www.youtube.com/watch?v=lpuYZ5EUyS8&list=PLgJhDSE2ZLxaY_DigHeiIDC1cD09rXgJv&index=2) to watch a data scientist go through the exercises

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', 
                      sep='|', index_col='user_id')

### Step 4. See the first 10 entries

In [4]:
users.head()

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

### Step 5. What is the number of observations in the dataset?

In [4]:
# Solution 1

4622

In [5]:
# Solution 2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

### Step 6. What is the number of columns in the dataset?

5

### Step 7. Print the name of all the columns.

Index([u'order_id', u'quantity', u'item_name', u'choice_description',
       u'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

              order_id  quantity
item_name
Chicken Bowl    713926       761

### Step 10. For the most-ordered item, how many items were ordered?

              order_id  quantity
item_name
Chicken Bowl    713926       761

### Step 11. What was the most ordered item in the choice_description column?

                    order_id  quantity
choice_description
[Diet Coke]           123455       159

### Step 12. How many items were orderd in total?

4972

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

dtype('O')

#### Step 13.b. Create a lambda function and change the type of item price

#### Step 13.c. Check the item price type

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

Revenue was: $39237.02

### Step 15. How many orders were made in the period?

1834

### Step 16. What is the average revenue amount per order?

In [31]:
# Solution 1

21.394231188658654

In [32]:
# Solution 2

21.394231188658654

### Step 17. How many different items are sold?

50